AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Eventual bank account initialization
  
Globals:
  Function:
    Timeout: 10

Resources:
  AccountInitFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dynamo-handler/
      Handler: app.handler
      Runtime: nodejs18.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
      Events:
        CreateOrUpdateItem:
          Type: HttpApi
          Properties:
            Path: /accounts
            Method: PUT

  ItemsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: account_id
        Type: Number
      TableName: account

Outputs:
  ApiEndpoint:
    Description: "The invoke URL for the HTTP API, using PUT"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/accounts"
  Function:
    Description: "DynamoDB handler function ARN"
    Value: !GetAtt AccountInitFunction.Arn
